# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-properties-fs:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    PLUGIN_NAME: vdk-properties-fs
  extends: .build-plugin

build-py37-vdk-properties-fs:
  extends: .build-vdk-properties-fs
  image: "python:3.7"


build-py38-vdk-properties-fs:
  extends: .build-vdk-properties-fs
  image: "python:3.8"


build-py39-vdk-properties-fs:
  extends: .build-vdk-properties-fs
  image: "python:3.9"

build-py310-vdk-properties-fs:
  extends: .build-vdk-properties-fs
  image: "python:3.10"

build-py311-vdk-properties-fs:
  extends: .build-vdk-properties-fs
  image: "python:3.11"

release-vdk-properties-fs:
  variables:
    PLUGIN_NAME: vdk-properties-fs
  extends: .release-plugin
