# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-dags:
  variables:
    PLUGIN_NAME: vdk-dags
  extends: .build-plugin

build-py37-vdk-dags:
  extends: .build-vdk-dags
  image: "python:3.7"

build-py311-vdk-dags:
  extends: .build-vdk-dags
  image: "python:3.11"

release-vdk-dags:
  variables:
    PLUGIN_NAME: vdk-dags
  extends: .release-plugin
