# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0



.build-vdk-meta-jobs:
  variables:
    PLUGIN_NAME: vdk-meta-jobs
  extends: .build-plugin

build-py37-vdk-meta-jobs:
  extends: .build-vdk-meta-jobs
  image: "python:3.7"

build-py311-vdk-meta-jobs:
  extends: .build-vdk-meta-jobs
  image: "python:3.11"

release-vdk-meta-jobs:
  variables:
    PLUGIN_NAME: vdk-meta-jobs
  extends: .release-plugin
