# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-lineage-model:
  variables:
    PLUGIN_NAME: vdk-lineage-model
  extends: .build-plugin

build-py37-vdk-lineage-model:
  extends: .build-vdk-lineage-model
  image: "python:3.7"


build-py38-vdk-lineage-model:
  extends: .build-vdk-lineage-model
  image: "python:3.8"


build-py39-vdk-lineage-model:
  extends: .build-vdk-lineage-model
  image: "python:3.9"

build-py310-vdk-lineage-model:
  extends: .build-vdk-lineage-model
  image: "python:3.10"

build-py311-vdk-lineage-model:
  extends: .build-vdk-lineage-model
  image: "python:3.11"

release-vdk-lineage-model:
  variables:
    PLUGIN_NAME: vdk-lineage-model
  extends: .release-plugin
