# Copyright 2023-2025 Broadcom
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-structlog:
  variables:
    PLUGIN_NAME: vdk-structlog
  extends: .build-plugin

build-py37-vdk-structlog:
  extends: .build-vdk-structlog
  image: "python:3.7"

build-py312-vdk-structlog:
  extends: .build-vdk-structlog
  image: "python:3.12"

release-vdk-structlog:
  variables:
    PLUGIN_NAME: vdk-structlog
  extends: .release-plugin
