# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-structlog:
  variables:
    PLUGIN_NAME: vdk-structlog
  extends: .build-plugin

build-py37-vdk-structlog:
  extends: .build-vdk-structlog
  image: "python:3.7"

build-py311-vdk-structlog:
  extends: .build-vdk-structlog
  image: "python:3.11"

release-vdk-structlog:
  variables:
    PLUGIN_NAME: vdk-structlog
  extends: .release-plugin
