# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-trino:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    PLUGIN_NAME: vdk-trino
  extends: .build-plugin

build-py37-vdk-trino:
  extends: .build-vdk-trino
  image: "python:3.7"


build-py38-vdk-trino:
  extends: .build-vdk-trino
  image: "python:3.8"


build-py39-vdk-trino:
  extends: .build-vdk-trino
  image: "python:3.9"

build-py310-vdk-trino:
  extends: .build-vdk-trino
  image: "python:3.10"

build-vdk-trino-on-vdk-core-release:
  variables:
    PLUGIN_NAME: vdk-trino
  extends: .build-plugin-on-vdk-core-release
  image: "python:3.9"

release-vdk-trino:
  variables:
    PLUGIN_NAME: vdk-trino
  extends: .release-plugin
