{{- /*
  Copyright 2021-2023 VMware, Inc.
  SPDX-License-Identifier: Apache-2.0
 */}}

{{- if and (.Values.operationsUi.username) (.Values.operationsUi.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pipelines-control-service.fullname" . }}-operations-ui-repo-creds
  namespace: {{ .Release.Namespace }}
  labels: {{- include "pipelines-control-service.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "operationsUiPullSecretJson" . }}
{{- end }}
