# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-logging-json:
  variables:
    PLUGIN_NAME: vdk-logging-json
  extends: .build-plugin

build-py37-vdk-logging-json:
  extends: .build-vdk-logging-json
  image: "python:3.7"


build-py38-vdk-logging-json:
  extends: .build-vdk-logging-json
  image: "python:3.8"


build-py39-vdk-logging-json:
  extends: .build-vdk-logging-json
  image: "python:3.9"

build-py310-vdk-logging-json:
  extends: .build-vdk-logging-json
  image: "python:3.10"

release-vdk-logging-json:
  variables:
    PLUGIN_NAME: vdk-logging-json
  extends: .release-plugin
