title: Versatile Data Kit Documentation
url: https://tozka.github.io/versatile-data-kit/

plugins:
  - jekyll-sitemap
  - jekyll-relative-links

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

relative_links:
  enabled: true
  collections: true

markdown: kramdown
kramdown:
  input: GFM

theme: minima

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
