{{- if not .Values.deploymentGitUrl }}
apiVersion: v1
kind: Secret
metadata:
   name: {{ .Release.Name }}-git-properties
   labels:
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
      helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
   annotations:
      # This is what defines this resource as a hook. Without this line, the
      # resource is considered part of the release.
      helm.sh/hook: pre-install
      helm.sh/hook-weight: "1"
      helm.sh/hook-delete-policy: before-hook-creation
      helm.sh/resource-policy: keep
data:
   git-repo-name: {{ .Values.deploymentGitRepoName | default uuidv4 | b64enc | quote }}
   git-server: {{ "github.com/versatile-data-kit-jobs" | b64enc | quote }}
   git-username: {{ "versatile-data-kit-jobs" | b64enc | quote }}
   git-access-token: {{ "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" | b64enc | quote }}
{{- end }}