# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


.build-quickstart-vdk:
  variables:
    PLUGIN_NAME: quickstart-vdk
  extends: .build-plugin

build-py37-quickstart-vdk:
  extends: .build-quickstart-vdk
  image: "python:3.7"

build-py38-quickstart-vdk:
  extends: .build-quickstart-vdk
  image: "python:3.8"

build-py39-quickstart-vdk:
  extends: .build-quickstart-vdk
  image: "python:3.9"

build-py310-quickstart-vdk:
  extends: .build-quickstart-vdk
  image: "python:3.10"


release-quickstart-vdk:
  variables:
    PLUGIN_NAME: quickstart-vdk
  extends: .release-plugin

release-vdk-image-quickstart-vdk:
  variables:
    PLUGIN_NAME: quickstart-vdk
  extends: .release-vdk-image
