@startuml
!include <awslib/AWSSimplified>
!include <awslib/General/User>
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites/vault.puml

User(engineer, "User", " ")

rectangle "K8s Cluster" {
   rectangle "Data Jobs Namespace" {
     component "Data Job" as dj #silver {
     }
   }
   rectangle "Control Service Namespace" {
      component "Control Service" as cs #teal {
       rectangle "Data Jobs Deployment API" as data_jobs_deployment_api
      }
  }
}

database "\nCockroachDB\n" as DB #silver

engineer --> data_jobs_deployment_api : " deploys data job\n(API call)"
data_jobs_deployment_api --> DB : " stores complete data job\ndeployment configuration"
data_jobs_deployment_api --> dj : " creates\n Kubernetes CronJob "

legend bottom left
  | <#teal> changed component |
  | <#silver> existing component |
endlegend

@enduml
