@startuml
!include <awslib/AWSSimplified>
!include <awslib/General/User>
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites/vault.puml

User(engineer, "User", " ")

rectangle "K8s Cluster" {
   rectangle "Data Jobs Namespace" {
     component "Data Job" as dj #silver {
     }
   }
   rectangle "Control Service Namespace" {
      component "Control Service" as cs #silver {
       rectangle "Cron Jobs Synchronizer" as  cron_jobs_synchronizer #LightGreen
       rectangle "Data Jobs Deployment API" as data_jobs_deployment_api #LightSkyBlue
      }
  }
  database "\nCockroachDB\n" as DB #silver
}

engineer --> data_jobs_deployment_api : " deploys or updates data job\n(API call)"
data_jobs_deployment_api --> DB : " stores complete data job\ndeployment configuration"
cron_jobs_synchronizer --> cron_jobs_synchronizer : "(Async Process)"
cron_jobs_synchronizer --> dj : " creates or updates\n Kubernetes Cron Jobs"


legend bottom left
  | <#LightSkyBlue> changed component |
  | <#silver> existing component |
  | <#LightGreen> new component |
endlegend

@enduml
