# Specifies a base image containing installed and ready to use VDK
# https://docs.docker.com/develop/develop-images/dockerfile_best-practices

ARG vdk_base_python_image

FROM $vdk_base_python_image

WORKDIR /vdk

ENV VDK_VERSION $vdk_version

# Install VDK
ARG vdk_version
ARG vdk_package
ARG pip_extra_index_url

# Install bash
RUN apt-get update && apt-get install -y bash && echo "Bash installed successfully" || echo "Bash installation failed"

# Set default shell to bash
SHELL ["/bin/bash", "-c"]

# Default command
CMD ["/bin/bash"]

# Force a snapshot with a no-op RUN command
RUN echo "Forcing snapshot"


RUN pip install --extra-index-url $pip_extra_index_url $vdk_package==$vdk_version


