# Copyright 2023-2024 Broadcom
# SPDX-License-Identifier: Apache-2.0

# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0



.build-vdk-ipython:
  variables:
    PLUGIN_NAME: vdk-ipython
  extends: .build-plugin

build-py37-vdk-ipython:
  extends: .build-vdk-ipython
  image: "python:3.7"

build-py311-vdk-ipython:
  extends: .build-vdk-ipython
  image: "python:3.11"

release-vdk-ipython:
  variables:
    PLUGIN_NAME: vdk-ipython
  extends: .release-plugin
