

# Copyright 2023-2025 Broadcom
# SPDX-License-Identifier: Apache-2.0

.build-vdk-ingest-file:
  variables:
    PLUGIN_NAME: vdk-ingest-file
  extends: .build-plugin

build-py37-vdk-ingest-file:
  extends: .build-vdk-ingest-file
  image: "python:3.7"

build-py312-vdk-ingest-file:
  extends: .build-vdk-ingest-file
  image: "python:3.12"

release-vdk-ingest-file:
  variables:
    PLUGIN_NAME: vdk-ingest-file
  extends: .release-plugin
