# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
from unittest.mock import Mock

import pytest
from vdk.internal.builtin_plugins.ingestion.source.auto_generated import (
    AutoGeneratedDataSourceConfiguration,
)
from vdk.internal.builtin_plugins.ingestion.source.wrong_plugin import (
    DataSourcesConfigurationPlugin,
)
from vdk.internal.core.config import ConfigurationBuilder


@pytest.fixture
def mock_config_builder():
    return ConfigurationBuilder()


@pytest.fixture
def mock_core_context():
    mock_context = Mock()
    return mock_context


@pytest.fixture
def mock_data_source_factory():
    mock_factory = Mock()
    mock_ds = Mock()
    mock_ds.config_class = AutoGeneratedDataSourceConfiguration
    mock_factory.list.return_value = [mock_ds]
    return mock_factory


def test_data_sources_configuration_plugin(
    mock_data_source_factory, mock_config_builder, mock_core_context
):
    plugin = DataSourcesConfigurationPlugin(mock_data_source_factory)

    plugin.vdk_configure(mock_config_builder)
    mock_config_builder.set_value("auto_generated_num_records", 123)
    mock_core_context.configuration = mock_config_builder.build()
    plugin.vdk_initialize(mock_core_context)

    assert mock_data_source_factory.list()[0].config_instance is not None
    assert mock_data_source_factory.list()[0].config_instance.num_records == 123
