CREATE TABLE TEST_TABLE (
    ID NUMBER,
    STR_DATA VARCHAR2(255),
    INT_DATA NUMBER,
    FLOAT_DATA FLOAT,
    BOOL_DATA NUMBER(1),
    TIMESTAMP_DATA TIMESTAMP,
    DECIMAL_DATA DECIMAL(14,8),
    PRIMARY KEY(ID))
