

# Copyright 2023-2025 Broadcom
# SPDX-License-Identifier: Apache-2.0

.build-vdk-lineage:
  variables:
    PLUGIN_NAME: vdk-lineage
  extends: .build-plugin

build-py37-vdk-lineage:
  extends: .build-vdk-lineage
  image: "python:3.7"

build-py312-vdk-lineage:
  extends: .build-vdk-lineage
  image: "python:3.12"

release-vdk-lineage:
  variables:
    PLUGIN_NAME: vdk-lineage
  extends: .release-plugin
