# Copyright 2023-2024 Broadcom
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-oracle:
  variables:
    PLUGIN_NAME: vdk-oracle
  extends: .build-plugin-dind

build-py37-vdk-oracle:
  extends: .build-vdk-oracle
  image: "python:3.7"

build-py311-vdk-oracle:
  extends: .build-vdk-oracle
  image: "python:3.11"

build-py312-vdk-oracle:
  extends: .build-vdk-oracle
  image: "python:3.12"

release-vdk-oracle:
  variables:
    PLUGIN_NAME: vdk-oracle
  extends: .release-plugin
