# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-ingest-http:
  variables:
    PLUGIN_NAME: vdk-ingest-http
  extends: .build-plugin

build-py37-vdk-ingest-http:
  extends: .build-vdk-ingest-http
  image: "python:3.7"


build-py38-vdk-ingest-http:
  extends: .build-vdk-ingest-http
  image: "python:3.8"


build-py39-vdk-ingest-http:
  extends: .build-vdk-ingest-http
  image: "python:3.9"

build-py310-vdk-ingest-http:
  extends: .build-vdk-ingest-http
  image: "python:3.10"

build-py311-vdk-ingest-http:
  extends: .build-vdk-ingest-http
  image: "python:3.11"

build-vdk-ingest-http-on-vdk-core-release:
  variables:
    PLUGIN_NAME: vdk-ingest-http
  extends: .build-plugin-on-vdk-core-release
  image: "python:3.9"

release-vdk-ingest-http:
  variables:
    PLUGIN_NAME: vdk-ingest-http
  extends: .release-plugin
