# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-notebook:
  variables:
    PLUGIN_NAME: vdk-notebook
  extends: .build-plugin

build-py37-vdk-notebook:
  extends: .build-vdk-notebook
  image: "python:3.7"


build-py38-vdk-notebook:
  extends: .build-vdk-notebook
  image: "python:3.8"

build-py39-vdk-notebook:
  extends: .build-vdk-notebook
  image: "python:3.9"

build-py310-vdk-notebook:
  extends: .build-vdk-notebook
  image: "python:3.10"

release-vdk-notebook:
  variables:
    PLUGIN_NAME: vdk-notebook
  extends: .release-plugin
