{{- /*
  Copyright 2023-2024 Broadcom
  SPDX-License-Identifier: Apache-2.0
 */}}

{{- if .Values.datajobslimitrange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: data-jobs-limit-range
  namespace: {{ template "pipelines-control-service.deploymentK8sNamespace" . }}
spec:
  limits:
    - max:
        cpu: {{ default "4" .Values.datajobslimitrange.max.cpu }}
        memory: {{ default "8gi" .Values.datajobslimitrange.max.memory }}
      type: Pod
{{- end }}
