# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "pipelines-control-service.fullname" . }}
  namespace: {{ template "pipelines-control-service.controlK8sNamespace" . }}
  labels: {{- include "pipelines-control-service.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ template "pipelines-control-service.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "pipelines-control-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
