# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.rbac.create .Values.rbac.datajobsDeployment.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "pipelines-control-service.fullname" . }}-datajobs
  namespace: {{ template "pipelines-control-service.deploymentK8sNamespace" . }}
  labels: {{- include "pipelines-control-service.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "secrets"
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
      - "cronjobs"
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
      - deletecollection
{{- end -}}
