{{- /*
  Copyright 2021-2023 VMware, Inc.
  SPDX-License-Identifier: Apache-2.0
 */}}

{{- if and .Values.serviceAccount.create .Values.rbac.create .Values.rbac.datajobsDeployment.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "pipelines-control-service.fullname" . }}-datajobs
  namespace: {{ template "pipelines-control-service.deploymentK8sNamespace" . }}
  labels: {{- include "pipelines-control-service.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ template "pipelines-control-service.fullname" . }}-datajobs
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "pipelines-control-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
