{{- /*
  Copyright 2021-2023 VMware, Inc.
  SPDX-License-Identifier: Apache-2.0
 */}}

{{- if .Values.deploymentDataJobBaseImage.password }}
apiVersion: v1
kind: Secret
metadata:
  name: builder-secrets
  namespace: {{ .Values.controlK8sNamespace }}
  labels: {{- include "pipelines-control-service.labels" . | nindent 4 }}
type: Opaque
stringData:
{{/* Within this section any set of properties can be set and then used in a job builder image
at the moment the only one set is extra_auth: Within this property docker config should be included to connect to the registry used to pull the image from. */}}
  extra_auth: {{- printf " ', \"%s\": {\"auth\": \"%s\"}'" .Values.deploymentDataJobBaseImage.registry (printf "%s:%s" .Values.deploymentDataJobBaseImage.username .Values.deploymentDataJobBaseImage.password | b64enc) }}
{{- end }}
