# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

## Create a secret with Kerberos keytab for authentication if kerberos authentication flag is turned on.
## The keytab file contents are set from the values.yaml file and are intended to be populated by an env
## variable.
{{- if .Values.security.kerberos.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-authenticator-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "pipelines-control-service.labels" . | nindent 4 }}
type: Opaque
data:
  authenticator-keytab-file.keytab: {{ default "" .Values.security.kerberos.kerberosServiceKeytab | b64enc | quote }}
{{- end }}
