{{- if (include "shouldCreateVdkSdkDockerRepoSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pipelines-control-service.vdkSdkDockerRepoSecretName" . }}
  namespace: {{ .Values.deploymentK8sNamespace }}
  labels: {{- include "pipelines-control-service.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "vdkSdkImagePullSecretJson" . }}
{{- end }}
