{{- /*
  Copyright 2021-2023 VMware, Inc.
  SPDX-License-Identifier: Apache-2.0
 */}}

## Create a secret with Vault credentials for storing Secrets only if externalSecretName is not supplied.
## If any of the fields are empty, we fall-back to defaults (f.e. local dev environment)
{{- if not .Values.secrets.vault.externalSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipelines-control-service.vaultSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "pipelines-control-service.labels" . | nindent 4 }}
data: {{- include "pipelines-control-service.vaultSecret" . | nindent 2 }}
{{- end }}
