## Create a secret with Kerberos keytab for authentication if kerberos authentication flag is turned on.
## The keytab and krb5.conf files' contents are set from the values.yaml chart and are intended to be
## populated by an environment variable.
{{- if .Values.security.kerberos.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-authenticator-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "pipelines-control-service.labels" . | nindent 4 }}
type: Opaque
data:
  authenticator-keytab-file.keytab: {{ default "" .Values.security.kerberos.keytabFileContents | b64enc | quote }}
  krb5.conf: {{ default "" .Values.security.kerberos.krb5ConfigContents | b64enc | quote }}
{{- end }}
