{{- /*
  Copyright 2023-2025 Broadcom
  SPDX-License-Identifier: Apache-2.0
 */}}

{{- if and (or (eq .Values.deploymentDockerRegistryType "generic") (eq .Values.deploymentDockerRegistryType "jfrog")) .Values.deploymentDockerRegistryUsernameReadOnly .Values.deploymentDockerRegistryPasswordReadOnly }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pipelines-control-service.fullname" . }}-docker-repo-creds
  namespace: {{ .Values.deploymentK8sNamespace }}
  labels: {{- include "pipelines-control-service.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretJson" . }}
{{- end }}
