# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pipelines-control-service.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "pipelines-control-service.labels" . | nindent 4 }}
type: Opaque
data:
  kadmin-password: {{ default "" .Values.credentials.kerberosKadminPassword | b64enc | quote }}
  deployment-kubeconfig: {{ default "" .Values.deploymentK8sKubeconfig | b64enc | quote }}
  krb5.conf: {{ default "" .Values.credentials.kerberosKrb5Conf | b64enc | quote }}
  vdk-options.ini: {{ default "" .Values.vdkOptions | b64enc | quote }}
