# Copyright 2023-2025 Broadcom
# SPDX-License-Identifier: Apache-2.0

# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-storage:
  variables:
    PLUGIN_NAME: vdk-storage
  extends: .build-plugin

build-py37-vdk-storage:
  extends: .build-vdk-storage
  image: "python:3.7"

build-py312-vdk-storage:
  extends: .build-vdk-storage
  image: "python:3.12"

release-vdk-storage:
  variables:
    PLUGIN_NAME: vdk-storage
  extends: .release-plugin
