# Copyright 2023-2025 Broadcom
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-duckdb:
  variables:
    PLUGIN_NAME: vdk-duckdb
  extends: .build-plugin

build-py37-vdk-duckdb:
  extends: .build-vdk-duckdb
  image: "python:3.7"

build-py312-vdk-duckdb:
  extends: .build-vdk-duckdb
  image: "python:3.12"

release-vdk-duckdb:
  variables:
    PLUGIN_NAME: vdk-duckdb
  extends: .release-plugin
