


# Copyright 2023-2024 Broadcom
# SPDX-License-Identifier: Apache-2.0

.build-vdk-sqlite:
  variables:
    PLUGIN_NAME: vdk-sqlite
  extends: .build-plugin

build-py37-vdk-sqlite:
  extends: .build-vdk-sqlite
  image: "python:3.7"

build-py312-vdk-sqlite:
  extends: .build-vdk-sqlite
  image: "python:3.12"

release-vdk-sqlite:
  variables:
    PLUGIN_NAME: vdk-sqlite
  extends: .release-plugin
