# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"


.build-vdk-sqlite:
  variables:
    PLUGIN_NAME: vdk-sqlite
  extends: .build-plugin

build-py37-vdk-sqlite:
  extends: .build-vdk-sqlite
  image: "python:3.7"


build-py38-vdk-sqlite:
  extends: .build-vdk-sqlite
  image: "python:3.8"


build-py39-vdk-sqlite:
  extends: .build-vdk-sqlite
  image: "python:3.9"

build-py310-vdk-sqlite:
  extends: .build-vdk-sqlite
  image: "python:3.10"

build-py311-vdk-sqlite:
  extends: .build-vdk-sqlite
  image: "python:3.11"

release-vdk-sqlite:
  variables:
    PLUGIN_NAME: vdk-sqlite
  extends: .release-plugin
