# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-kerberos-auth:
  variables:
    PLUGIN_NAME: vdk-kerberos-auth
  extends: .build-plugin

build-py37-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.7"


build-py38-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.8"


build-py39-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.9"

build-py310-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.10"

release-vdk-kerberos-auth:
  variables:
    PLUGIN_NAME: vdk-kerberos-auth
  extends: .release-plugin
