# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0



.build-vdk-kerberos-auth:
  variables:
    PLUGIN_NAME: vdk-kerberos-auth
  script:
    - openssl version
    # krb5-user is a requirement for the tests because the Kerberos server is configured via kadmin
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y krb5-user openssl build-essential checkinstall zlib1g-dev
    - openssl version
    - wget https://www.openssl.org/source/openssl-3.1.4.tar.gz
    - tar -xzvf openssl-3.1.4.tar.gz && cd openssl-3.1.4
    - ./config
    - make
    - make install
    - ldconfig
    - cd ..
    - openssl version
    - /usr/local/bin/openssl version
    - echo $PATH
    - export PATH=/usr/local/bin:$PATH
    - openssl version
    - ln -sf /usr/local/bin/openssl /usr/bin/openssl
    - pip install https://github.com/wbond/oscrypto/archive/d5f3437ed24257895ae1edd9e503cfb352e635a8.zi
    - openssl version
    - !reference [.build-plugin, script]
  extends: .build-plugin-dind

build-py37-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.7"

build-py311-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.11"

#build-vdk-kerberos-auth-on-vdk-core-release:
#  variables:
#    PLUGIN_NAME: vdk-kerberos-auth
#  extends: .build-plugin-on-vdk-core-release
#  image: "python:3.9"

release-vdk-kerberos-auth:
  variables:
    PLUGIN_NAME: vdk-kerberos-auth
  extends: .release-plugin
