# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-kerberos-auth:
  image: docker:19.03.8
  services:
    - docker:19.03.8-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    PLUGIN_NAME: vdk-kerberos-auth
  script:
    - apt-get update
    - apt-get install -y krb5-user
  extends: .build-plugin

build-py37-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.7"

build-py38-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.8"

build-py39-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.9"

build-py310-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.10"

release-vdk-kerberos-auth:
  variables:
    PLUGIN_NAME: vdk-kerberos-auth
  extends: .release-plugin
