

# Copyright 2023-2025 Broadcom
# SPDX-License-Identifier: Apache-2.0

.build-vdk-kerberos-auth:
  variables:
    PLUGIN_NAME: vdk-kerberos-auth
  script:
    # krb5-user is a requirement for the tests because the Kerberos server is configured via kadmin
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y krb5-user
#   the line below needs to be removed when cryptolib 1.3.1 or 1.4.0 is released https://community.snowflake.com/s/article/Python-Connector-fails-to-connect-with-LibraryNotFoundError-Error-detecting-the-version-of-libcrypto
    - pip install https://github.com/wbond/oscrypto/archive/d5f3437ed24257895ae1edd9e503cfb352e635a8.zip
    - !reference [.build-plugin, script]
  extends: .build-plugin-dind

#build-py37-vdk-kerberos-auth:
#  extends: .build-vdk-kerberos-auth
#  image: "python:3.7"
#
#build-py312-vdk-kerberos-auth:
#  extends: .build-vdk-kerberos-auth
#  image: "python:3.12"

#build-vdk-kerberos-auth-on-vdk-core-release:
#  variables:
#    PLUGIN_NAME: vdk-kerberos-auth
#  extends: .build-plugin-on-vdk-core-release
#  image: "python:3.9"

release-vdk-kerberos-auth:
  variables:
    PLUGIN_NAME: vdk-kerberos-auth
  extends: .release-plugin
