# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0



.build-vdk-kerberos-auth:
  variables:
    PLUGIN_NAME: vdk-kerberos-auth
  script:
    # krb5-user is a requirement for the tests because the Kerberos server is configured via kadmin
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y krb5-user
    - !reference [.build-plugin, script]
  extends: .build-plugin-dind

build-py37-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.7"

build-py311-vdk-kerberos-auth:
  extends: .build-vdk-kerberos-auth
  image: "python:3.11"

#build-vdk-kerberos-auth-on-vdk-core-release:
#  variables:
#    PLUGIN_NAME: vdk-kerberos-auth
#  extends: .build-plugin-on-vdk-core-release
#  image: "python:3.9"

release-vdk-kerberos-auth:
  variables:
    PLUGIN_NAME: vdk-kerberos-auth
  extends: .release-plugin
