# Copyright 2023-2024 Broadcom
# SPDX-License-Identifier: Apache-2.0

# Copyright 2021-2024 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

resources:
  limits:
    cpu: 2000m
    memory: 4000Mi
  requests:
    cpu: 1000m
    memory: 2000Mi
