# https://docs.docker.com/develop/develop-images/dockerfile_best-practices\
# Creating data job base image with support for Oracle.

ARG base_image=python:3.7-slim
FROM $base_image

# Set the working directory
WORKDIR /job


# Install native dependencies so that requirements in requirements.txt can be installed
# some (like openssl) should be pre-installed in the base image but let's be explicit
RUN set -ex \
       && apt-get update \
       && apt-get -y install --no-install-recommends \
              build-essential openssl g++
