# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0



.build-vdk-server:
  variables:
    PLUGIN_NAME: vdk-server
  extends: .build-plugin

build-py37-vdk-server:
  extends: .build-vdk-server
  image: "python:3.7"

build-py311-vdk-server:
  extends: .build-vdk-server
  image: "python:3.11"

release-vdk-server:
  variables:
    PLUGIN_NAME: vdk-server
  extends: .release-plugin
