

# Copyright 2023-2025 Broadcom
# SPDX-License-Identifier: Apache-2.0

.build-vdk-server:
  variables:
    PLUGIN_NAME: vdk-server
  extends: .build-plugin

build-py37-vdk-server:
  extends: .build-vdk-server
  image: "python:3.7"

build-py312-vdk-server:
  extends: .build-vdk-server
  image: "python:3.12"

release-vdk-server:
  variables:
    PLUGIN_NAME: vdk-server
  extends: .release-plugin
