# https://docs.docker.com/develop/develop-images/dockerfile_best-practices
FROM photon:latest

ARG base_image
COPY --from=$base_image /usr/local/ /usr/local/

# Set the working directory
WORKDIR /job

# Install native dependencies
RUN yum install shadow build-essential libffi gcc krb5-devel e2fsprogs-devel glibc-devel -y
