# https://docs.docker.com/develop/develop-images/dockerfile_best-practices
ARG base_image
FROM $base_image as base

FROM photon:latest

# Copies essential binaries, libraries, headers, and Python files from the base Python image,
# excluding build dependencies.
COPY --from=base /usr/local/ /usr/local/

# Set the working directory
WORKDIR /job

# Uninstall native dependencies
RUN yum erase toybox -y

# Install native dependencies
RUN yum install shadow build-essential -y

RUN set -ex \
      && mkdir -p /opt/lib/native  \
      && yum -y install libaio curl unzip \
      && curl --insecure --output oracle-instantclient.zip https://download.oracle.com/otn_software/linux/instantclient/2110000/instantclient-basic-linux.x64-21.10.0.0.0dbru.zip \
      && unzip oracle-instantclient.zip -d /opt/lib/native/oracle && rm -f oracle-instantclient.zip \
      && sh -c "echo /opt/lib/native/oracle/instantclient_20_10 > /etc/ld.so.conf.d/oracle-instantclient.conf" \
      && ldconfig \
      && yum remove -y curl unzip
