

# Copyright 2023-2024 Broadcom
# SPDX-License-Identifier: Apache-2.0

.build-vdk-dag:
  variables:
    PLUGIN_NAME: vdk-dag
  extends: .build-plugin

build-py37-vdk-dag:
  extends: .build-vdk-dag
  image: "python:3.7"

build-py312-vdk-dag:
  extends: .build-vdk-dag
  image: "python:3.12"

release-vdk-dag:
  variables:
    PLUGIN_NAME: vdk-dag
  extends: .release-plugin
