# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
from dataclasses import fields
from datetime import datetime
from typing import Any
from typing import Dict
from typing import Iterator
from typing import List

from vdk.internal.builtin_plugins.ingestion.source.config import config_class
from vdk.internal.builtin_plugins.ingestion.source.config import config_field
from vdk.internal.builtin_plugins.ingestion.source.data_source import DataSourcePayload
from vdk.internal.builtin_plugins.ingestion.source.data_source import IDataSource
from vdk.internal.builtin_plugins.ingestion.source.data_source import (
    IDataSourceConfiguration,
)
from vdk.internal.builtin_plugins.ingestion.source.data_source import IDataSourceStream
from vdk.internal.builtin_plugins.ingestion.source.factory import register_data_source
from vdk.internal.builtin_plugins.ingestion.source.state import IDataSourceState


@config_class(
    name="auto_generated", description="Configuration for Auto generated data source"
)
class AutoGeneratedDataSourceConfiguration(IDataSourceConfiguration):
    num_records: int = config_field(
        description="Number of records to return", default=2
    )
    include_metadata: bool = config_field(
        description="If true autogenerated metadata is included in the response",
        default=False,
    )
    num_streams: int = config_field(
        description="The number of streams the data source would have", default=1
    )


class AutoGeneratedDataSourceStream(IDataSourceStream):
    def name(self) -> str:
        return str(self._stream_number)

    def __init__(
        self, config: AutoGeneratedDataSourceConfiguration, stream_number: int
    ):
        self._config = config
        self._stream_number = stream_number
        self._data = self._generate_test_data()

    def _generate_test_data(self) -> List[DataSourcePayload]:
        generated_data = []
        for i in range(self._config.num_records):
            data = {
                "id": i,
                "name": f"Stream_{self._stream_number}_Name_{i}",
                "stream": self._stream_number,
            }
            metadata = (
                {"timestamp": datetime.now()} if self._config.include_metadata else {}
            )
            generated_data.append(DataSourcePayload(data=data, metadata=metadata))
        return generated_data

    def read(self) -> Iterator[List[DataSourcePayload]]:
        for i in range(0, len(self._data), 1):
            yield self._data[i]


@register_data_source("auto-generated-data", AutoGeneratedDataSourceConfiguration)
class AutoGeneratedDataSource(IDataSource):
    def __init__(self):
        self._streams = []

    def connect(self, config: IDataSourceConfiguration, state: IDataSourceState):
        if not isinstance(config, AutoGeneratedDataSourceConfiguration):
            raise RuntimeError(
                f"config type must be {AutoGeneratedDataSourceConfiguration}"
            )
        self._streams = [
            AutoGeneratedDataSourceStream(config, i) for i in range(config.num_streams)
        ]

    def disconnect(self):
        self._streams = []

    def streams(self) -> List[IDataSourceStream]:
        return self._streams
