# Copyright 2021 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-impala:
  variables:
    PLUGIN_NAME: vdk-impala
  extends: .build-plugin-dind

build-py37-vdk-impala:
  extends: .build-vdk-impala
  image: "python:3.7"


build-py38-vdk-impala:
  extends: .build-vdk-impala
  image: "python:3.8"


build-py39-vdk-impala:
  extends: .build-vdk-impala
  image: "python:3.9"

build-py310-vdk-impala:
  extends: .build-vdk-impala
  image: "python:3.10"


build-vdk-impala-on-vdk-core-release:
  variables:
    PLUGIN_NAME: vdk-impala
  extends: .build-plugin-on-vdk-core-release
  image: "python:3.9"


release-vdk-impala:
  variables:
    PLUGIN_NAME: vdk-impala
  extends: .release-plugin
