# Copyright 2023-2024 Broadcom
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-data-sources:
  variables:
    PLUGIN_NAME: vdk-data-sources
  extends: .build-plugin

build-py37-vdk-data-sources:
  extends: .build-vdk-data-sources
  image: "python:3.7"

build-py312-vdk-data-sources:
  extends: .build-vdk-data-sources
  image: "python:3.12"

release-vdk-data-sources:
  variables:
    PLUGIN_NAME: vdk-data-sources
  extends: .release-plugin
