

# Copyright 2023-2025 Broadcom
# SPDX-License-Identifier: Apache-2.0

.build-vdk-logging-format:
  variables:
    PLUGIN_NAME: vdk-logging-format
  extends: .build-plugin

#build-py37-vdk-logging-format:
#  extends: .build-vdk-logging-format
#  image: "python:3.7"
#
#build-py311-vdk-logging-format:
#  extends: .build-vdk-logging-format
#  image: "python:3.11"

release-vdk-logging-format:
  variables:
    PLUGIN_NAME: vdk-logging-format
  extends: .release-plugin
