# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
image: "python:3.7"

.build-vdk-snowflake:
  variables:
    PLUGIN_NAME: vdk-snowflake
  extends: .build-plugin

build-py37-vdk-snowflake:
  extends: .build-vdk-snowflake
  image: "python:3.7"

build-py311-vdk-snowflake:
  extends: .build-vdk-snowflake
  image: "python:3.11"

release-vdk-snowflake:
  variables:
    PLUGIN_NAME: vdk-snowflake
  extends: .release-plugin
