# Copyright 2023-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0
# This file is auto-generated by Hatchling. As such, do not:
#   - modify
#   - track in version control e.g. be sure to add to .gitignore
__version__ = VERSION = "0.1.0"
