title: Versatile Data Kit Documentation
url: https://tozka.github.io/versatile-data-kit/

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

markdown: kramdown
kramdown:
  input: GFM

theme: minima

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
