# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

.build-vdk-audit:
  variables:
    PLUGIN_NAME: vdk-audit
  extends: .build-plugin

build-py38-vdk-audit:
  extends: .build-vdk-audit
  image: "python:3.8"

build-py311-vdk-audit:
  extends: .build-vdk-audit
  image: "python:3.11"

release-vdk-audit:
  variables:
    PLUGIN_NAME: vdk-audit
  extends: .release-plugin
