

# Copyright 2023-2025 Broadcom
# SPDX-License-Identifier: Apache-2.0

.build-vdk-plugin-control-cli:
  variables:
    PLUGIN_NAME: vdk-plugin-control-cli
  extends: .build-plugin

build-py37-vdk-plugin-control-cli:
  extends: .build-vdk-plugin-control-cli
  image: "python:3.7"

build-py312-vdk-plugin-control-cli:
  extends: .build-vdk-plugin-control-cli
  image: "python:3.12"

build-vdk-plugin-control-cli-on-vdk-core-release:
  variables:
    PLUGIN_NAME: vdk-plugin-control-cli
  extends: .build-plugin-on-vdk-core-release
  image: "python:3.9"

release-vdk-plugin-control-cli:
  variables:
    PLUGIN_NAME: vdk-plugin-control-cli
  extends: .release-plugin
