# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0



.build-vdk-plugin-control-cli:
  variables:
    PLUGIN_NAME: vdk-plugin-control-cli
  extends: .build-plugin

build-py37-vdk-plugin-control-cli:
  extends: .build-vdk-plugin-control-cli
  image: "python:3.7"

build-py311-vdk-plugin-control-cli:
  extends: .build-vdk-plugin-control-cli
  image: "python:3.11"

build-vdk-plugin-control-cli-on-vdk-core-release:
  variables:
    PLUGIN_NAME: vdk-plugin-control-cli
  extends: .build-plugin-on-vdk-core-release
  image: "python:3.9"

release-vdk-plugin-control-cli:
  variables:
    PLUGIN_NAME: vdk-plugin-control-cli
  extends: .release-plugin
