# Copyright 2021-2023 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-csv:
  variables:
    PLUGIN_NAME: vdk-csv
  extends: .build-plugin

build-py37-vdk-csv:
  extends: .build-vdk-csv
  image: "python:3.7"

build-py311-vdk-csv:
  extends: .build-vdk-csv
  image: "python:3.11"

build-vdk-csv-on-vdk-core-release:
  variables:
    PLUGIN_NAME: vdk-csv
  extends: .build-plugin-on-vdk-core-release
  image: "python:3.9"

release-vdk-csv:
  variables:
    PLUGIN_NAME: vdk-csv
  extends: .release-plugin
