# Copyright 2023-2024 Broadcom
# SPDX-License-Identifier: Apache-2.0

image: "python:3.7"

.build-vdk-data-source-git:
  variables:
    PLUGIN_NAME: vdk-data-source-git
  extends: .build-plugin

build-py37-vdk-data-source-git:
  extends: .build-vdk-data-source-git
  image: "python:3.7"

build-py312-vdk-data-source-git:
  extends: .build-vdk-data-source-git
  image: "python:3.12"

release-vdk-data-source-git:
  variables:
    PLUGIN_NAME: vdk-data-source-git
  extends: .release-plugin
