# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

.build-vdk-audit-hook:
  variables:
    PLUGIN_NAME: vdk-audit-hook
  extends: .build-plugin

build-py38-vdk-audit-hook:
  extends: .build-vdk-audit-hook
  image: "python:3.8"

build-py39-vdk-audit-hook:
  extends: .build-vdk-audit-hook
  image: "python:3.9"

build-py310-vdk-audit-hook:
  extends: .build-vdk-audit-hook
  image: "python:3.10"

release-vdk-audit-hook:
  variables:
    PLUGIN_NAME: vdk-audit-hook
  extends: .release-plugin
